name: Release 

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm ci

      - name: Generate changelog
        id: changelog
        uses: docker://marcosperona/git-changelog:latest
        with:
          format: markdown
          output-file: CHANGELOG.md

      - name: Archive source code
        uses: actions/upload-artifact@v2
        with:
          name: source-code
          path: .

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changelog
            $(cat CHANGELOG.md)

            ## Version
            Version: `$(node -pe "require('./package.json').version")`

            ## Release Files
            * [Source code](https://github.com/zodtf/ptero-sync/archive/${{ github.ref }}.zip)

          draft: false
          prerelease: ${{ contains(github.ref, 'prerelease') }}
          
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ptero-sync-${{ github.ref }}.zip
          asset_name: ptero-sync-${{ github.ref }}.zip
          asset_content_type: application/zip
